# Generated by Django 3.0.5 on 2020-07-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('firstname', models.CharField(default=None, max_length=20)),
                ('lastname', models.CharField(default=None, max_length=20)),
                ('username', models.CharField(default=None, max_length=20)),
                ('emailid', models.EmailField(default=None, max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=20)),
                ('state', models.CharField(default=None, max_length=20)),
                ('zipcode', models.CharField(default=None, max_length=20)),
                ('aggrement', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Registration',
            },
        ),
    ]
