# Generated by Django 3.0.5 on 2020-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('username', models.TextField()),
                ('emailid', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('city', models.TextField()),
                ('zipcode', models.TextField()),
                ('aggrement', models.BooleanField()),
            ],
            options={
                'db_table': 'Registration',
            },
        ),
    ]
