# Generated by Django 3.0.5 on 2020-06-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='aggrement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='emailid',
            field=models.EmailField(default=None, max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='firstname',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lastname',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='zipcode',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
