# Generated by Django 3.0.5 on 2020-06-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200629_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='aggrement',
            field=models.BooleanField(default=True),
        ),
    ]
