# Generated by Django 3.0.5 on 2020-07-15 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('problem', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='user/images/')),
                ('address', models.TextField(max_length=1000)),
                ('zip', models.CharField(max_length=15)),
                ('ward', models.CharField(max_length=20)),
                ('solved', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.datetime(2020, 7, 15, 11, 36, 25, 835547))),
            ],
            options={
                'db_table': 'Complaint',
            },
        ),
    ]
