# Generated by Django 3.0.5 on 2020-07-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('problems', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('address', models.TextField(max_length=1000)),
                ('zip', models.CharField(max_length=15)),
                ('ward', models.CharField(max_length=20)),
                ('solved', models.BooleanField(default=False)),
                ('unsolved', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Complaint',
            },
        ),
    ]
