# Generated by Django 3.0.5 on 2020-07-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='problems',
            new_name='problem',
        ),
    ]
