# Generated by Django 3.0.5 on 2020-07-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200709_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='unsolved',
        ),
    ]
