# Generated by Django 3.0.5 on 2020-07-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
