# Generated by Django 3.0.5 on 2020-07-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
    ]
