# Generated by Django 3.0.5 on 2020-07-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_login_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resetpassword',
            fields=[
                ('emailid', models.EmailField(default=None, max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('activeotp', models.BooleanField(default=False)),
                ('lastchange', models.CharField(max_length=30)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
    ]
