# Generated by Django 3.0.5 on 2020-07-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_resetpassword'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resetpassword',
            table='Resetpassword',
        ),
    ]
